package observability

import (
	"sync"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// MetricsRegistry holds all Prometheus metrics for FM modules
type MetricsRegistry struct {
	// CM metrics
	CMEventsReceived   prometheus.Counter
	CMEventsDuplicated prometheus.Counter
	CMEventsForwarded  prometheus.Counter
	CMValidationErrors prometheus.Counter

	// DM metrics
	DMEventsProcessed       prometheus.Counter
	DMConsistencyChecks     prometheus.Counter
	DMConsistencyViolations prometheus.Counter
	DMConstructsStored      prometheus.Counter

	// GM metrics
	GMGoalStatesGenerated prometheus.Counter
	GMCacheHits           prometheus.Counter
	GMCacheMisses         prometheus.Counter

	// DAL metrics
	DALProgramAttempts prometheus.Counter
	DALProgramSuccesses prometheus.Counter
	DALProgramFailures  prometheus.Counter

	// Latency histograms (buckets in seconds)
	CMPipelineLatency prometheus.Histogram
	DMProcessLatency  prometheus.Histogram
	GMCompositeLatency prometheus.Histogram
	DALProgramLatency  prometheus.Histogram

	mu sync.RWMutex
}

// NewMetricsRegistry creates a new metrics registry
func NewMetricsRegistry() *MetricsRegistry {
	return &MetricsRegistry{
		// CM Counters
		CMEventsReceived: promauto.NewCounter(prometheus.CounterOpts{
			Name: "fm_cm_events_received_total",
			Help: "Total events received by Config Management",
		}),
		CMEventsDuplicated: promauto.NewCounter(prometheus.CounterOpts{
			Name: "fm_cm_events_duplicated_total",
			Help: "Total duplicate events filtered by Config Management",
		}),
		CMEventsForwarded: promauto.NewCounter(prometheus.CounterOpts{
			Name: "fm_cm_events_forwarded_total",
			Help: "Total events forwarded by Config Management",
		}),
		CMValidationErrors: promauto.NewCounter(prometheus.CounterOpts{
			Name: "fm_cm_validation_errors_total",
			Help: "Total validation errors in Config Management",
		}),

		// DM Counters
		DMEventsProcessed: promauto.NewCounter(prometheus.CounterOpts{
			Name: "fm_dm_events_processed_total",
			Help: "Total events processed by Data Management",
		}),
		DMConsistencyChecks: promauto.NewCounter(prometheus.CounterOpts{
			Name: "fm_dm_consistency_checks_total",
			Help: "Total consistency checks performed",
		}),
		DMConsistencyViolations: promauto.NewCounter(prometheus.CounterOpts{
			Name: "fm_dm_consistency_violations_total",
			Help: "Total consistency violations detected",
		}),
		DMConstructsStored: promauto.NewCounter(prometheus.CounterOpts{
			Name: "fm_dm_constructs_stored_total",
			Help: "Total constructs stored in registry",
		}),

		// GM Counters
		GMGoalStatesGenerated: promauto.NewCounter(prometheus.CounterOpts{
			Name: "fm_gm_goal_states_generated_total",
			Help: "Total goal states generated by Goal State Management",
		}),
		GMCacheHits: promauto.NewCounter(prometheus.CounterOpts{
			Name: "fm_gm_cache_hits_total",
			Help: "Total goal state cache hits",
		}),
		GMCacheMisses: promauto.NewCounter(prometheus.CounterOpts{
			Name: "fm_gm_cache_misses_total",
			Help: "Total goal state cache misses",
		}),

		// DAL Counters
		DALProgramAttempts: promauto.NewCounter(prometheus.CounterOpts{
			Name: "fm_dal_program_attempts_total",
			Help: "Total device programming attempts",
		}),
		DALProgramSuccesses: promauto.NewCounter(prometheus.CounterOpts{
			Name: "fm_dal_program_successes_total",
			Help: "Total successful device programming operations",
		}),
		DALProgramFailures: promauto.NewCounter(prometheus.CounterOpts{
			Name: "fm_dal_program_failures_total",
			Help: "Total failed device programming operations",
		}),

		// Latency Histograms (buckets in seconds: 1ms, 5ms, 10ms, 50ms, 100ms, 500ms, 1s, 5s)
		CMPipelineLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "fm_cm_pipeline_latency_seconds",
			Help:    "Event pipeline processing latency in seconds",
			Buckets: []float64{0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0},
		}),
		DMProcessLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "fm_dm_process_latency_seconds",
			Help:    "Data management event processing latency in seconds",
			Buckets: []float64{0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0},
		}),
		GMCompositeLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "fm_gm_composite_latency_seconds",
			Help:    "Goal state composition latency in seconds",
			Buckets: []float64{0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0},
		}),
		DALProgramLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "fm_dal_program_latency_seconds",
			Help:    "Device programming latency in seconds",
			Buckets: []float64{0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0},
		}),
	}
}

// IncrementCounter increments a counter by 1
func (mr *MetricsRegistry) IncrementCounter(counter prometheus.Counter) {
	if counter != nil {
		counter.Inc()
	}
}

// IncrementCounterBy increments a counter by a specific amount
func (mr *MetricsRegistry) IncrementCounterBy(counter prometheus.Counter, value float64) {
	if counter != nil {
		counter.Add(value)
	}
}

// RecordLatency records a latency observation in seconds
func (mr *MetricsRegistry) RecordLatency(histogram prometheus.Histogram, seconds float64) {
	if histogram != nil {
		histogram.Observe(seconds)
	}
}

// GetCounterValue returns the current value of a counter (for testing)
func (mr *MetricsRegistry) GetCounterValue(counter prometheus.Counter) float64 {
	if counter == nil {
		return 0
	}
	// Note: Prometheus doesn't expose direct value reading, so this is a placeholder
	// In production, scrape /metrics and parse the value
	return 0
}
